---
title: 'CRCJ 3000 (Online) – Applied Statistics'
author: "Nicholas Vietto"
date: "Spring 2024"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

**Instructor:** Nicholas Vietto  
**Contact:** nvietto@unomaha.edu  
**Office Hours:** By appointment via Zoom  
**Class Meeting Times:** NA     
**Classroom:** NA      

## Course Description

The purpose is to introduce the basic principles of data visualization and statistical inference in order to provide a foundation for quantitative analysis. Researchers and practitioners in social science (e.g., criminology and criminal justice) need to have an understanding of statistical analysis and data management in their skill set. This course addresses fundamental concepts and applied knowledge statistical analysis.

## Textbook and Resources

- **Required Textbook:** Gau, J.M. (2019). Statistics for Criminology and Criminal Justice (3rd ed). Los Angeles, CA: SAGE Publications. ISBN: 9781506391786

- Supplementary Resources: Will be uploaded to the course page on Canvas 

## Assignments, Exams, and Grading

**Chapter Review Assignments (50 points):**
Students will complete 10 chapter review assignments over the course of the semester. Each assignment is worth 5 points and contains questions worth between 0.5 and 2.5 points each.

All chapter review assignments will be completed on Canvas and can be found under the module for that week. You can only submit the assignment once, but you can take as much time as you need. Assignments on Canvas must be completed by 11:59pm on Sunday each week.

**Chapter Math Uploads (8 points):**
Eight of your weekly chapter review assignments will require you to complete math calculations by hand. If math is required, you will need to take a picture of your handwritten calculations and submit them to me via the corresponding math upload assignment. You may also hand in your work in person on the Monday after the assignment is due if you prefer. By submitting these assignments, I can give partial credit on your review assignments if your math is correct even though your answer is not.

**Exams (42 points):**
There will be two exams this semester: Exam 1 (21 points) over chapters 1-8 and a final exam (21 points) over chapters 9-13. Details will be provided closer exam day.

**Grading scale: A (90-100), B (80-89), C (70-79), D (60-69), F (0-59).**

## Policies

- **Late Work:** If you miss an assignment due to your own illness (including mental health) or the illness of a family member or close friend, please let me know within 48 hours (use email provided above). Depending on circumstances, I may allow you to make up an assignment within one week of the due date or to submit an additional assignment in lieu of a missed assignment. If some circumstance arises during the semester that may require you to miss several activities or assignments, please let me know as soon as possible.

- **Academic Integrity:** Maintaining the highest standards of academic integrity is crucial for fostering a fair and ethical learning environment. I take academic dishonesty and lack of integrity seriously and will follow all procedures that are stated by the University of Nebraska-Omaha's [\textcolor{red}{academic integrity policy}](https://www.unomaha.edu/campus-policies/academic-integrity.php).

- **Accommodations:** Reasonable accommodations are provided for students who are registered with Accessibility Services Center (ASC) and make their requests sufficiently in advance. For more information, contact ASC (Location: 104 H&K, Phone: 402.554.2872, Email: unoaccessibility@unomaha.edu.). In addition, Counseling and Psychological Services (CAPS) are free and confidential for enrolled students. For more information, contact CAPS at 402.554.2409, H&K 101, Monday – Friday, 8a.m. - 5p.m. Please also visit our [\textcolor{blue}{website}](https://caps.unomaha.edu) to learn more. If you are in crisis or dealing with thoughts of suicide, please call 402.554.2409 (and press "2" after-hours) to speak to a counselor immediately.

## Schedule

*This syllabus is subject to change at the discretion of the instructor. Any changes will be communicated to students.*

**Week 1** - Introduction to Statistics

* Review syllabus and take welcome survey
* Chapter 1 - Readings and Resources

**Week 2**, Variables and Levels of Measurement

* Chapter 2 - Readings and Resources 
* **Chapter 1 & 2 Review Problems due on Sunday at 11:59pm**

**Week 3**, Organizing, Displaying, and Presenting Data

* Chapter 3 - Readings and Resources 

**Week 4**, Measures of Central Tendency

* Chapter 4 - Readings and Resources 
* **Chapter 3 & 4 Review Problems due on Sunday at 11:59pm**

**Week 5**, Measures of Dispersion

* Chapter 5 - Readings and Resources
* **Chapter 5 Review Problems are due on Sunday at 11:59pm**
* *Remember to submit the math upload with problems*

**Week 6**, Probability 

* Chapter 6 - Readings and Resources
* **Chapter 6 Review Problems are due on Sunday at 11:59pm**
* *Remember to submit the math upload with problems*

**Week 7**, Population, Sample, and Sampling Distributions

*  Chapter 7 - Readings and Resources

**Week 8**, Point Estimates and Confidence Intervals

*  Chapter 8 - Readings and Resources
* **Chapter 7 & 8 Review Problems are due on Sunday at 11:59pm**
* *Remember to submit the math upload with problems*

**Week 9**, Spring Break 

**Week 10**, Exam 1

* **Exam 1 is due on Sunday at 11:59pm**
* *Remember to submit the math upload with problems*

**Week 11**, Introduction to Hypothesis Testing and Chi-Square (Part 1)

*  Chapter 9 - Readings and Resources

**Week 12**, Introduction to Hypothesis Testing and Chi-Square (Part 2)

*  Chapter 10 - Readings and Resources
* **Chapter 9 & 10 Review Problems are due on Sunday at 11:59pm**
* *Remember to submit the math upload with problems*

**Week 13**, Independent-Samples T Tests (Part 1)

*  Chapter 11 - Readings and Resources
* **Chapter 11 Review Problems are due on Sunday at 11:59pm**
* *Remember to submit the math upload with problems*

**Week 14**, Independent-Samples T Tests (Part 2)

* Chapter 11 - Readings and Resources
* **Chapter 11 Review Problems are due on Sunday at 11:59pm**
* *Remember to submit the math upload with problems*

**Week 15**, ANOVA and Correlations 

* Chapter 12 and 13 Readings and Resources 
* Take two weeks to complete these assignments 

**Week 16**, Prep Week

* Study, study, study..... and sleep 
* **Chapter 12 and 13 Review Problems are due on Sunday at 11:59pm**
* *Remember to submit the math upload with problems*


**Week 17**, Exam 2

 
