---
title: 'CRCJ 3000 – Applied Statistics'
author: "Nicholas Vietto"
date: "Spring 2024"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

**Instructor:** Nicholas Vietto  
**Contact:** nvietto@unomaha.edu  
**Office Hours:** By appointment via Zoom  
**Class Meeting Times:** NA    
**Classroom:** NA   

## Course Description

This course aims to introduce fundamental principles of data visualization and statistical inference, serving as a cornerstone for quantitative analysis. The curriculum will emphasizes the significance of statistical analysis and data management in research and professional practice within criminology and criminal justice. Introducing the essential concepts and practical applications, students will develop a robust skill set in statistical analysis during the course.

## Textbook and Course Materials 

- **Required Textbook:** Gau, J.M. (2019). Statistics for Criminology and Criminal Justice (3rd ed). Los Angeles, CA: SAGE Publications. ISBN: 9781506391786

- Supplementary Resources: Will be uploaded to the course page on Canvas 

- We will be using R Statistical Software throughout the course via [\textcolor{blue}{Posit Cloud}](https://posit.cloud). It is completely free and I will designate class time to walk through setting this up.

## Assignments, Exams, and Grading

**Chapter Assignments (50%):**

Students will complete chapter review assignments over the course of the semester. Assignments will be completed on Canvas and can be found under the module for that week. You will have to either snap a picture of your handwritten calculations and submit them to me via the corresponding math upload assignment or hand in your work in person on the Monday after the assignment is due. Assignments on Canvas must be completed by 11:59pm on Sunday each week.

**Exams (50%):**
There will be two exams this semester: Exam 1 (Chapters 1 - 6) and a Exam 2 (Chapters 7 - 13). Details will be provided closer exam day. I have structured in two review days before each of the exams, during these review sessions we will recap the major concepts and allow time to walk through concepts that are not clear.

**Grading scale: A (90-100), B (80-89), C (70-79), D (60-69), F (0-59).**

## Policies

- **Attendance:** Attendance in this course is considered an integral part of the learning experience and contributes to your overall success. Engaging in class discussions, group activities, and participating in hands-on experiences are essential for a comprehensive understanding of the subject matter. While I do not take attendance, those who **attend and actively participate** will benefit from extensions, extra credit opportunities, and final grade curves I often provide at the end of the semester. 

- **Active participation** is a crucial element in our classroom dynamics, I've found it to be among the most effective ways for students to truly benefit from our shared learning experience. While I strongly urge and anticipate your verbal contributions during class, it's equally important to recognize that engaged and supportive listening is a valuable form of participation.

- **Late Work:** If you miss an assignment due to your own illness (including mental health) or the illness of a family member or close friend, please let me know within 48 hours (use email provided above). Depending on circumstances, I may allow you to make up an assignment within one week of the due date or to submit an additional assignment in lieu of a missed assignment. If some circumstance arises during the semester that may require you to miss several activities or assignments, please let me know as soon as possible.

- **Academic Integrity:** Maintaining the highest standards of academic integrity is crucial for fostering a fair and ethical learning environment. I take academic dishonesty and lack of integrity seriously and will follow all procedures that are stated by the University of Nebraska-Omaha's [\textcolor{red}{academic integrity policy}](https://www.unomaha.edu/campus-policies/academic-integrity.php).

- **Accommodations:** Reasonable accommodations are provided for students who are registered with Accessibility Services Center (ASC) and make their requests sufficiently in advance. For more information, contact ASC (Location: 104 H&K, Phone: 402.554.2872, Email: unoaccessibility@unomaha.edu.). In addition, Counseling and Psychological Services (CAPS) are free and confidential for enrolled students. For more information, contact CAPS at 402.554.2409, H&K 101, Monday – Friday, 8a.m. - 5p.m. Please also visit our [\textcolor{blue}{website}](https://caps.unomaha.edu) to learn more. If you are in crisis or dealing with thoughts of suicide, please call 402.554.2409 (and press "2" after-hours) to speak to a counselor immediately.

## Schedule

*This syllabus is subject to change at the discretion of the instructor. Any changes will be communicated to students.*

**Week 1** - 01/22 - 01/16

* Tuesday: Introductions, Syllabus Review
* Thursday: Chapter 1

**Week 2** - 01/29 - 02/02

* Tuesday: Chapter 1
* Thursday: Chapter 2


**Week 3**, 02/05 - 02/09

* Tuesday: Chapter 2
* Thursday: Chapter 3


**Week 4**, 02/12 - 02/16

* Tuesday: Chapter 3
* Thursday: Chapter 4

**Week 5**, 02/19 - 02/23

* Tuesday: Chapter 4
* Thursday: Chapter 5 
* **Chapter 4 Review Problems are due on Sunday at 11:59pm**


**Week 6**, 02/26 - 03/01

* Tuesday: Chapter 5 
* Thursday: Chapter 6
* **Chapter 5 Review Problems are due on Sunday at 11:59pm**

**Week 7**, 03/04 - 03/08

* Tuesday: Chapter 6
* Thursday: Review for Exam 1
* **Chapter 6 Review Problems are due on Sunday at 11:59pm**

**Week 8**, 03/11 - 03/15

* Spring Break

**Week 9**, 03/18 - 03/22 

* Tuesday: **Exam 1 - Chapters 1-6**
* Thursday: Chapter 7

**Week 10**, 03/25 - 03/29

* Tuesday: Chapter 7
* Thursday: Chapter 8
* **Chapter 7 Review Problems are due on Sunday at 11:59pm**

**Week 11**, 04/01 - 04/05

* Tuesday: Chapter 8
* Thursday: Chapter 9
* **Chapter 8 Review Problems are due on Sunday at 11:59pm**

**Week 12**, 04/08 - 04/12

* Tuesday: Chapter 9
* Thursday: Chapter 10
* **Chapter 9 Review Problems are due on Sunday at 11:59pm**

**Week 13**, 04/15 - 04/19

* Tuesday: Chapter 10
* Thursday: Chapter 11
* **Chapter 10 Review Problems are due on Sunday at 11:59pm**

**Week 14**, 04/22 - 04/26

* Tuesday: Chapter 11
* Thursday: Chapter 12
* **Chapter 11 Review Problems are due on Sunday at 11:59pm**

**Week 15**, 04/29 - 05/03

* Tuesday: Chapter 12
* Thursday: Chapter 13
* **Chapter 12 Review Problems are due on Sunday at 11:59pm**

**Week 16**, 05/06 - 05/10 

* Tuesday: Chapter 13
* Thursday: Review for Exam 2
* **Chapter 13 Review Problems are due on Sunday at 11:59pm**

**Week 17**, 05/13 - 05/17

* **Exam 2 - Chapters 7 - 13**



