---
title: "Chapter 8 Homework"
format: pdf
editor: source
---

1.)

A pharmaceutical company is conducting a clinical trial to test the effectiveness of a new drug designed to lower blood pressure. They recruit **100 participants** with hypertension and administer the new drug to them for six weeks. After the trial period, the researchers measure the participants' blood pressure levels and calculate the mean decrease in blood pressure along with its standard deviation.

The researchers want to estimate the true mean decrease in blood pressure for the entire population of individuals with hypertension. They decide to construct a 95% confidence interval for this mean decrease.

Given the sample **mean decrease in blood pressure is 10 mmHg** with a sample **standard deviation of 3 mmHg,** construct the **95% confidence interval** for the true mean decrease in blood pressure. Then, interpret the interval in the context of the problem.



\pagebreak


2.) 

A nutritionist wants to determine the average number of calories in a specific type of energy bar. She selects a random sample of **8 energy bars** from a particular brand and measures the number of calories in each bar.

Construct a **95% confidence interval** for the true mean number of calories in this type of energy bar. Then, interpret the interval in the context of the problem. 

(hint 1: sample size)

(hint 2: Find the mean, variance, sd, then plug in values to find the CI)


```{r}
#| echo: false

mean <- 200
sd <- 20

set.seed(041624)
value <- rnorm(8, mean, sd)

data <- data.frame(
  "Energy Bar" = paste0("Energy Bar_", 1:8),
  "Calories" = round(value, 0)
)

data

```





